-- =============================================================================
-- Chapter titles + side-story update for Usogui Fansite
-- Run this in Supabase SQL Editor (or psql).
-- Safe to re-run: upserts update titles, skips already-correct rows.
-- =============================================================================

-- Step 1: Widen the chapter number column to support decimals (e.g. 20.5 side stories).
-- This is a no-op if it's already numeric.
ALTER TABLE chapter ALTER COLUMN number TYPE numeric(5,1) USING number::numeric(5,1);

-- Step 2: Upsert all chapters — updates title for existing rows, inserts new ones.
INSERT INTO chapter (number, title, "isVerified") VALUES
  (1,     'Gambler',                                                       false),
  (2,     'Eat The Illegal Loan',                                          false),
  (3,     'The Personal Information Trap',                                 false),
  (4,     'The Secret',                                                    false),
  (5,     'The Value Of Things',                                           false),
  (6,     'The Abandoned Building Game',                                   false),
  (7,     'Everything Is A Gamble',                                        false),
  (8,     'The Mind Breaks Down',                                          false),
  (9,     'The Pleasure Of Murder',                                        false),
  (10,    'A Feast Of Screams',                                            false),
  (11,    'The Man Called Usogui',                                         false),
  (12,    'Awakening',                                                     false),
  (13,    'Terror Of The Mask',                                            false),
  (14,    'Surpassing The Leader',                                         false),
  (15,    'Plan B',                                                        false),
  (16,    'Begging For Life...',                                           false),
  (17,    'Wipe The Blood',                                                false),
  (18,    'The Final Plan',                                                false),
  (19,    'Cling To Your ''Life''',                                        false),
  (20,    'A Game Of Tag In Hell',                                         false),
  (20.5,  'Volume 2 Side Story',                                           false),
  (21,    'Who Am I?',                                                     false),
  (22,    'Atone For Your Sins',                                           false),
  (23,    'Make A Comeback',                                               false),
  (24,    'Get Used To Money',                                             false),
  (25,    'Sharpen Your Teeth',                                            false),
  (26,    'Bet',                                                           false),
  (27,    'The Value Of A Human',                                          false),
  (28,    'Kind Advice',                                                   false),
  (29,    'Devour Him!',                                                   false),
  (30,    'Control The Money!',                                            false),
  (31,    'Fortune Is Unpredictable',                                      false),
  (31.5,  'Volume 3 Side Story',                                           false),
  (32,    'Kakerou''s Prodigy',                                            false),
  (33,    'A Vicious Killing Intent',                                      false),
  (34,    'The Devil Returns!',                                            false),
  (35,    'The Revolutionist Appears!!',                                   false),
  (36,    'Women''s Intuition',                                            false),
  (37,    'Only Those Noble Lives...',                                     false),
  (38,    'The Chosen One',                                                false),
  (39,    'Something''s Wrong...',                                         false),
  (40,    'Man Owners',                                                    false),
  (41,    'Hangman',                                                       false),
  (42,    'Leo',                                                           false),
  (42.5,  'Volume 4 Side Story',                                           false),
  (43,    'The 1st Game',                                                  false),
  (44,    'Five-elevenths',                                                false),
  (45,    'A 50/50 Battle',                                                false),
  (46,    'The Fight Against Time',                                        false),
  (47,    'Insane',                                                        false),
  (48,    'Kill The Many To Save The Few',                                 false),
  (49,    'The Struggle To Survive',                                       false),
  (50,    'The Misaligned Gear',                                           false),
  (51,    'A Toy That''s About To Break',                                  false),
  (52,    'Big Liar',                                                      false),
  (53,    'The Party Goes On...',                                          false),
  (53.5,  'Volume 5 Side Story',                                           false),
  (54,    'The Reaper''s Smile',                                           false),
  (55,    'Fate Of The Alien',                                             false),
  (56,    'The Zero Returns',                                              false),
  (57,    'The Way The World Works',                                       false),
  (58,    'Misjudged',                                                     false),
  (59,    'The Defeated',                                                  false),
  (60,    'Lion and Lion',                                                 false),
  (61,    'The Father''s Heart',                                           false),
  (62,    'For The First Time',                                            false),
  (63,    'Suddenly, Destiny...',                                          false),
  (64,    'The Truth Behind The Revolution',                               false),
  (64.5,  'Volume 6 Side Story',                                           false),
  (65,    'Getting Anxious',                                               false),
  (66,    'Sacrificing...',                                                false),
  (67,    'Luck Comes With...',                                            false),
  (68,    'The Hidden Ambition',                                           false),
  (69,    'Conditions',                                                    false),
  (70,    'Parent And Child',                                              false),
  (71,    'My Worth',                                                      false),
  (72,    'True Power',                                                    false),
  (73,    'Messenger',                                                     false),
  (74,    'Ideal',                                                         false),
  (75,    'Assassin''s Terms',                                             false),
  (75.5,  'Volume 7 Side Story',                                           false),
  (76,    'Merciful One',                                                  false),
  (77,    'Die Yobbo',                                                     false),
  (78,    'Ambitious Ones',                                                false),
  (79,    'Target',                                                        false),
  (80,    'Strange Rumors',                                                false),
  (81,    'Fateful Boundary',                                              false),
  (82,    'The Road of Bewilderment',                                      false),
  (83,    'Awakenings',                                                    false),
  (84,    'Demon King Advent',                                             false),
  (85,    'Infinite Chances',                                              false),
  (86,    'Inside of a Dream',                                             false),
  (86.5,  'Volume 8 Side Story',                                           false),
  (87,    'Bewildered Dog',                                                false),
  (88,    'Composition of the World',                                      false),
  (89,    'Enter the Labyrinth!',                                          false),
  (90,    'The Name of the Companion',                                     false),
  (91,    'The Best Seat in the House',                                    false),
  (92,    'Divine Possession',                                             false),
  (93,    'To Remember',                                                   false),
  (94,    'The Third Man',                                                 false),
  (95,    'Warning',                                                       false),
  (96,    'That Which Is Lost',                                            false),
  (97,    'A Decision Is Made...',                                         false),
  (97.5,  'Volume 9 Side Story',                                           false),
  (98,    'Order of the Ant',                                              false),
  (99,    'Contract for Life',                                             false),
  (100,   'A Big Mistake',                                                 false),
  (101,   'Order That Must Be Kept',                                       false),
  (102,   'The Grim Reaper Has Descended',                                 false),
  (103,   'The Corrupted Labyrinth',                                       false),
  (104,   'Purpose in Life',                                               false),
  (105,   'Lowlife',                                                       false),
  (106,   'The Devil of the Abandoned Building, Again',                    false),
  (107,   'Something That Is Obvious',                                     false),
  (108,   'Crash',                                                         false),
  (109,   'The Truth of the Rumor',                                        false),
  (109.5, 'Volume 10 Side Story',                                          false),
  (110,   'Feast of the Wild Beasts',                                      false),
  (111,   'Battle Royale',                                                 false),
  (112,   'Clash!!!',                                                      false),
  (113,   'Eternal Pandemonium',                                           false),
  (114,   'Next Stage',                                                    false),
  (115,   'L-File',                                                        false),
  (116,   'Natural Selection',                                             false),
  (117,   'Victory Is Inevitable',                                         false),
  (118,   'The Finest Scent',                                              false),
  (119,   'Monster: Minotaur',                                             false),
  (120,   'Probing Each Other',                                            false),
  (120.5, 'Volume 11 Side Story',                                          false),
  (121,   'The Thing That Follows',                                        false),
  (122,   'An Uneasy Atmosphere',                                          false),
  (123,   'A Savage Existence',                                            false),
  (124,   'Entering M Time!',                                              false),
  (125,   'A Pure Fight',                                                  false),
  (126,   'Intricate Thoughts',                                            false),
  (127,   'Superhuman v2',                                                 false),
  (128,   'Exchange for Life v2',                                          false),
  (129,   'Devil vs Superhuman v2',                                        false),
  (129.5, 'Volume 12 Side Story',                                          false),
  (130,   'Black v2',                                                      false),
  (131,   'Gear v2',                                                       false),
  (132,   'Trap v2',                                                       false),
  (133,   'A Failure Engraved',                                            false),
  (134,   'Various Stories',                                               false),
  (135,   'Encountering the Unknown',                                      false),
  (136,   'Characteristic of an Elite',                                    false),
  (137,   'The Depth of Prevision',                                        false),
  (138,   'The Thing Borrowed',                                            false),
  (139,   'Mixed Colors',                                                  false),
  (140,   'The Country Won''t Give Up',                                    false),
  (141,   'The Man Who Forsook His Pride',                                 false),
  (142,   'Things Lost to Darkness',                                       false),
  (142.5, 'Volume 13 Side Story',                                          false),
  (143,   'Minotaur',                                                      false),
  (144,   'Two Monsters',                                                  false),
  (145,   'Exterminate the Monster',                                       false),
  (146,   'Command',                                                       false),
  (147,   'Welcome Home',                                                  false),
  (148,   'Both Men Face Off',                                             false),
  (149,   'A Well-Plotted Revenge',                                        false),
  (150,   'The Qualification of the Fight',                                false),
  (151,   'Here Comes No.20!!',                                            false),
  (152,   'An Arranged Victory',                                           false),
  (153,   'A Depraved Heart',                                              false),
  (153.5, 'Volume 14 Side Story',                                          false),
  (154,   'The Vicious Virus',                                             false),
  (155,   'The Sealed Future',                                             false),
  (156,   'A Certain Proposition',                                         false),
  (157,   'Scream of Life',                                                false),
  (158,   'The Infernal Bull',                                             false),
  (159,   'Invalid Communication',                                         false),
  (160,   'Don''t Wanna Get In',                                           false),
  (161,   'Hellfire',                                                      false),
  (162,   'Exactly',                                                       false),
  (163,   'Signal',                                                        false),
  (164,   'Dead Or Alive',                                                 false),
  (164.5, 'Volume 15 Side Story',                                          false),
  (165,   'The Logic Of Killing',                                          false),
  (166,   'Genie''s Lamp',                                                 false),
  (167,   'Saving Face!',                                                  false),
  (168,   'Laser Pointer',                                                 false),
  (169,   'Invisible Evidence',                                            false),
  (170,   'The Light Of The Key Stone',                                    false),
  (171,   'Repentance',                                                    false),
  (172,   'Sign Of Resentment',                                            false),
  (173,   'Tempest Of Violence',                                           false),
  (174,   'After The Tempest',                                             false),
  (175,   'The Whisper Of Maternity',                                      false),
  (175.5, 'Volume 16 Side Story',                                          false),
  (176,   'Nim',                                                           false),
  (177,   'Certain-win Strategy',                                          false),
  (178,   'Can''t Read The Mood',                                          false),
  (179,   'The Hidden Past',                                               false),
  (180,   'A Made-up Scandal',                                             false),
  (181,   'Darkness Is Meant To Be Exposed',                               false),
  (182,   'TV Like Never Before',                                          false),
  (183,   'A Dark Strategy',                                               false),
  (184,   'People Covered In Blood',                                       false),
  (185,   'Consideration',                                                 false),
  (186,   'Slay The Devil',                                                false),
  (186.5, 'Volume 17 Side Story',                                          false),
  (187,   'The Darkness Is Calling',                                       false),
  (188,   'Darkness Comes Again',                                          false),
  (189,   'Nobody Knows',                                                  false),
  (190,   'Fool',                                                          false),
  (191,   'Rules And Hints',                                               false),
  (192,   'No More',                                                       false),
  (193,   'Lifeline',                                                      false),
  (194,   'Kakerou VS Kakerou',                                            false),
  (195,   'The Fate Of A Referee',                                         false),
  (196,   'Paralyzed Fist',                                                false),
  (197,   'The Best Taste',                                                false),
  (197.5, 'Volume 18 Side Story',                                          false),
  (198,   'Natural Disaster',                                              false),
  (199,   'Alibi Construction',                                            false),
  (200,   'The Fragment Of Memory',                                        false),
  (201,   'A Cowardly Heart',                                              false),
  (202,   'Pandora''s Box',                                                false),
  (203,   'A Calm Mind',                                                   false),
  (204,   'Empire Tower',                                                  false),
  (205,   'Meeting',                                                       false),
  (206,   'Referee Number Zero',                                           false),
  (207,   'Abominable...',                                                 false),
  (208,   'The Reckless Deputy Commissioner',                              false),
  (208.5, 'Volume 19 Side Story',                                          false),
  (209,   'The Bloody Chaplain',                                           false),
  (210,   'One In Ten Chance',                                             false),
  (211,   'A Mind-Game Nightmare',                                         false),
  (212,   'The Beast That Was Called Upon',                                false),
  (213,   'Wall Of Silver',                                                false),
  (214,   'The Narrator From Hell',                                        false),
  (215,   'Go And Go',                                                     false),
  (216,   'What''s The Meaning Behind Ambiguity?',                         false),
  (217,   'The Man Who Summons The Tempest',                               false),
  (218,   'Where''s The Hoarding House?',                                  false),
  (219,   'Eyes Of A Beast',                                               false),
  (219.5, 'Volume 20 Side Story',                                          false),
  (220,   'The Things I''m Going To Grasp',                                false),
  (221,   'The Two Fangs',                                                 false),
  (222,   'Keep It Around',                                                false),
  (223,   'The Lost Things...',                                            false),
  (224,   'The Inside And The Outside Of The prediction',                  false),
  (225,   'Quality And Quantity',                                          false),
  (226,   'Position',                                                      false),
  (227,   'The Chief Of The Private Funeral Division',                     false),
  (228,   'A Reaction Of Metal',                                           false),
  (229,   'Double-edged Sword',                                            false),
  (230,   'Gamblers',                                                      false),
  (230.5, 'Volume 21 Side Story',                                          false),
  (231,   'Party',                                                         false),
  (232,   'Bridge',                                                        false),
  (233,   'The Dancing Memory',                                            false),
  (234,   '13 Is...',                                                      false),
  (235,   'The Devil''s Number',                                           false),
  (236,   'Heihaizi',                                                      false),
  (237,   'Message In A Marco',                                            false),
  (238,   'Ranko Party',                                                   false),
  (239,   'A Tricky Party',                                                false),
  (240,   'Male Friends',                                                  false),
  (241,   'A Psycho Friend',                                               false),
  (241.5, 'Volume 22 Side Story',                                          false),
  (242,   'Gangbang',                                                      false),
  (243,   'Flurry Of Blades',                                              false),
  (244,   'Record 85',                                                     false),
  (245,   'Kurama Opens Wide',                                             false),
  (246,   'Prince Of Bruxism',                                             false),
  (247,   'The End Of The Party',                                          false),
  (248,   'Downfall Of Recklessness',                                      false),
  (249,   'Imaginary Buffaloes',                                           false),
  (250,   'Colosseum Box',                                                 false),
  (251,   'Even So, Humans Are Still Savage',                              false),
  (252,   'The Masked-devil Advent Again',                                 false),
  (252.5, 'Volume 23 Side Story',                                          false),
  (253,   'The Disrespected Sniper',                                       false),
  (254,   'Aufheben',                                                      false),
  (255,   'Special Journey',                                               false),
  (256,   'The River Of Death',                                            false),
  (257,   'Fake Poison Effect',                                            false),
  (258,   'Ten Bridges',                                                   false),
  (259,   'Victory Road',                                                  false),
  (260,   'The Sensational Tower',                                         false),
  (261,   'Invisible Holes',                                               false),
  (262,   'The Weird Feeling In Violence, Bullets And Deceit',             false),
  (263,   'The Final Decision',                                            false),
  (263.5, 'Volume 24 Side Story',                                          false),
  (264,   'The Cursed Fools',                                              false),
  (265,   '10 Second Battle',                                              false),
  (266,   'Conqueror',                                                     false),
  (267,   'Violence Withers',                                              false),
  (268,   'A Greedy Man',                                                  false),
  (269,   'The End And The Start',                                         false),
  (270,   'Fugitive',                                                      false),
  (271,   'Encircle The Bee',                                              false),
  (272,   'The People Who Leave Will Forget',                              false),
  (273,   'The Bee Acting In The Dark',                                    false),
  (273.5, 'Volume 25 Side Story',                                          false),
  (274,   'Tempting Coins',                                                false),
  (275,   'Creamer Number',                                                false),
  (276,   'The Risk That Shouldn''t Be',                                   false),
  (277,   'The Rising Price Of The Creamers',                              false),
  (278,   'The Man Who Ate Too Much',                                      false),
  (279,   'The Mind Of The Puppet',                                        false),
  (280,   'The Mysterious Guest',                                          false),
  (281,   'Happy',                                                         false),
  (282,   'Gallop',                                                        false),
  (283,   'Colombian Necktie',                                             false),
  (284,   'Outside Expectation',                                           false),
  (284.5, 'Volume 26 Side Story',                                          false),
  (285,   'Playing On A Boat',                                             false),
  (286,   'Implant Indirect Parasite',                                     false),
  (287,   'Start The Match',                                               false),
  (288,   'Kaji-kun→Kaji→You',                                             false),
  (289,   'Restraint And Astonishment',                                    false),
  (290,   'The Man Behind The Scenes',                                     false),
  (291,   'Ears As Branches, Eyes As Leaves',                              false),
  (292,   'Volley Again',                                                  false),
  (293,   'The Truth Of The Parasitism',                                   false),
  (294,   'Another Departure',                                             false),
  (295,   'The Backlit Bee',                                               false),
  (296,   'The Posture Of Expectation',                                    false),
  (297,   'A Straight Ball Of Madness',                                    false),
  (298,   'The Unseen Child',                                              false),
  (299,   'Joker',                                                         false),
  (300,   'Bloody Fetus',                                                  false),
  (301,   'The Envious Patriot',                                           false),
  (302,   'Intuition And Theory',                                          false),
  (303,   '4 Volleys Of Fire',                                             false),
  (304,   'Indiscriminate Firing Of Euphoria And Destruction',             false),
  (305,   'Curse, Fall, Seize',                                            false),
  (306,   'Perseverance',                                                  false),
  (306.5, 'Volume 28 Side Story',                                          false),
  (307,   'The Trap Of Eye Estimation',                                    false),
  (308,   'Looking Away Is Evil',                                          false),
  (309,   'The Klyuch(Key) To Turn It Around',                             false),
  (310,   'The Gentleman Of Nightmare',                                    false),
  (311,   'Boss & Boss',                                                   false),
  (312,   'Deja Vu',                                                       false),
  (313,   'The Million Yen Picture Book',                                  false),
  (314,   '''Referee'' Masahiko',                                          false),
  (315,   'Masahiko''s Judgement',                                         false),
  (316,   'This Name Again',                                               false),
  (317,   'The Devilish Member',                                           false),
  (317.5, 'Volume 29 Side Story',                                          false),
  (318,   'Bush And Cherry Blossom',                                       false),
  (319,   'Clams In The Fire',                                             false),
  (320,   'The Seed Production Of The Labyrinth',                          false),
  (321,   'First Contact, 2nd Time',                                       false),
  (322,   'The Owl In The Anthill',                                        false),
  (323,   'Chapter 1, Fin',                                                false),
  (324,   'Invitation Go',                                                 false),
  (325,   '卍(Ban)',                                                        false),
  (326,   '''Time'', ''Men'', ''Location''',                               false),
  (327,   'The Sweep Plan',                                                false),
  (328,   'Let The Match Begin',                                           false),
  (329,   'Protoporos',                                                    false),
  (330,   'Arata''s Puzzle',                                               false),
  (331,   'The Gambling Den In The Slave Dormitory',                       false),
  (332,   'Encirclement Of The 4 Gods',                                    false),
  (333,   'The Commencement Of The Silence',                               false),
  (334,   '''Certain Pass'' Or ''Duel''',                                  false),
  (335,   'The Scrambling Slaves',                                         false),
  (336,   'A Damn Slave',                                                  false),
  (337,   'The Ill Will Hidden Under The Lid',                             false),
  (338,   'It''s A Gamble, Right?',                                        false),
  (339,   'At The End Of A Frail Determination',                           false),
  (339.5, 'Volume 31 Side Story',                                          false),
  (340,   'King Of Slaves',                                                false),
  (341,   'Legendary Traveler',                                            false),
  (342,   'The Untouchable Line',                                          false),
  (343,   'Betting Ticket',                                                false),
  (344,   'Coordinator',                                                   false),
  (345,   'Weaklings',                                                     false),
  (346,   'The Deciding Match In Protoporos',                              false),
  (347,   'A Guaranteed Bet',                                              false),
  (348,   'Behind The Bear',                                               false),
  (349,   'The Exiled Ally',                                               false),
  (350,   'It''s Right Now!',                                              false),
  (350.5, 'Volume 32 Side Story',                                          false),
  (351,   'Single Task Specialist',                                        false),
  (352,   'Hunt The Beast',                                                false),
  (353,   'Antagonism',                                                    false),
  (354,   'Advantage Or Negligence',                                       false),
  (355,   'Because Anything Is Allowed',                                   false),
  (356,   'The Sneering Brother',                                          false),
  (357,   'The 卍(Ban) Initiator',                                          false),
  (358,   'Short-term Mutual Agreement And Compromises And Hope',          false),
  (359,   'The Taste Engraven',                                            false),
  (360,   'Leveling Up Love',                                              false),
  (361,   'The Fallen Fortress',                                           false),
  (361.5, 'Volume 33 Side Story',                                          false),
  (362,   'The Fortress Of Conspiracy',                                    false),
  (363,   'Instigating Each Other',                                        false),
  (364,   'Beatdown',                                                      false),
  (365,   'Game Of Contradiction',                                         false),
  (366,   'The 3rd Spear',                                                 false),
  (367,   'No Two Hearts Are The Same',                                    false),
  (368,   'Hard To Expose, Hard To Protect',                               false),
  (369,   'The Gambler Who Didn''t Pull',                                  false),
  (370,   'The Strength Of This Side',                                     false),
  (371,   'Explode',                                                       false),
  (372,   'A Profound Darkness',                                           false),
  (373,   'The Pierced Through Expectation',                               false),
  (374,   'Gamblers'' Stage',                                              false),
  (375,   'The Plan B Of Conspiracy',                                      false),
  (376,   'Festival Of The War',                                           false),
  (377,   'The Man Who Dominates The ''Outlaws''',                         false),
  (378,   'The Shooting Hunter',                                           false),
  (379,   'Deadlock',                                                      false),
  (380,   'The Legendary Bodyguard',                                       false),
  (381,   'Death In A Nanometer',                                          false),
  (382,   'Comprehension Of ''Non-violence''',                             false),
  (383,   'The Forbidden Power',                                           false),
  (384,   'Impurity',                                                      false),
  (384.5, 'Volume 35 Side Story',                                          false),
  (385,   'The Winner And The Hunter',                                     false),
  (386,   'Sanctuary',                                                     false),
  (387,   'Reward Of ''Violence''',                                        false),
  (388,   'The Sad News Within The Hollowness',                            false),
  (389,   'A King''s Game',                                                false),
  (390,   'No.0 Returns',                                                  false),
  (391,   'Hand Chopper',                                                  false),
  (392,   'The Plan To Become The ''King''',                               false),
  (393,   'Demon King',                                                    false),
  (394,   'The Mechanics Of Kings',                                        false),
  (395,   'Outbreak Of War',                                               false),
  (395.5, 'Volume 36 Side Story',                                          false),
  (396,   'The Theory Of The Stratagem',                                   false),
  (397,   'Nobuko''s Tactics',                                             false),
  (398,   'The Maggots Of The 6th Day',                                    false),
  (399,   'Great Fuss',                                                    false),
  (400,   'Collapse',                                                      false),
  (401,   'Island Of Turmoil',                                             false),
  (402,   'The Unifier',                                                   false),
  (403,   'Caught by time',                                                false),
  (404,   'Protoporos Nightmare',                                          false),
  (405,   'You''re Nowa, Right?',                                          false),
  (406,   'The Value Of 0',                                                false),
  (406.5, 'Volume 37 Side Story',                                          false),
  (407,   'The 卍(Ban) Island Thrown Into Chaos',                           false),
  (408,   'Surprise Attacks And Surprise Attacks And Surprise Attacks',    false),
  (409,   'Puzzle Of Chaos',                                               false),
  (410,   'Gakuto Dies For The Second Time',                               false),
  (411,   'The Excuse To Fight Back',                                      false),
  (412,   'Hero And Monster',                                              false),
  (413,   'The Fiery Dragon',                                              false),
  (414,   'The Man Made Of Lethal Weapons',                                false),
  (415,   'A New Nightmare',                                               false),
  (416,   'Cannibalism',                                                   false),
  (417,   'Meeting Again',                                                 false),
  (417.5, 'Volume 38 Side Story',                                          false),
  (418,   'The Zero, The Dragon',                                          false),
  (419,   'Each One''s Nightmare',                                         false),
  (420,   'Island Of Judgement',                                           false),
  (421,   'Conflagration',                                                 false),
  (422,   'Distortion',                                                    false),
  (423,   'Spinal Signature',                                              false),
  (424,   'Until That Day Comes',                                          false),
  (425,   'Proof Of Social Order',                                         false),
  (426,   'What He Swore To Protect',                                      false),
  (427,   'Prison Of Peace',                                               false),
  (428,   'The Man Who Won''t Run Away',                                   false),
  (429,   'An Island For Outsourcing',                                     false),
  (430,   'What Is Drowning?',                                             false),
  (431,   'Within The Silence',                                            false),
  (432,   'The First Round',                                               false),
  (433,   'Safe Zone',                                                     false),
  (434,   'The Straying Resolution',                                       false),
  (435,   'Drying Up',                                                     false),
  (436,   'During The Asphyxia',                                           false),
  (437,   '''39'' Or ''8''',                                               false),
  (438,   'Wish',                                                          false),
  (439,   'Awakening',                                                     false),
  (439.5, 'Volume 40 Side Story',                                          false),
  (440,   'The Knowledge Carved In Abomination',                           false),
  (441,   'The Provoking Gambler',                                         false),
  (442,   '''Ace Card'' Or ''Bait''',                                      false),
  (443,   'Respective Considerations',                                     false),
  (444,   'The Dazzling Panopticon',                                       false),
  (445,   '''The Calamity'' And ''The God Of Death''',                     false),
  (446,   'The Helping Hands',                                             false),
  (447,   'The Flesh''s Memory',                                           false),
  (448,   'Air Poker',                                                     false),
  (449,   'Witch Pain',                                                    false),
  (450,   'The Wedge Driven In',                                           false),
  (450.5, 'Volume 41 Side Story',                                          false),
  (451,   'The Shriek Of The Bird Of Prey',                                false),
  (452,   'Last 2',                                                        false),
  (453,   'The Strongest 4 Cards',                                         false),
  (454,   'A Small Trigger',                                               false),
  (455,   'The Thread Of Memories Woven Together',                         false),
  (456,   'The Suicidal Raise',                                            false),
  (457,   'Paradigm Shift',                                                false),
  (458,   'Folding From Instinct',                                         false),
  (459,   'The Hidden Landmine',                                           false),
  (460,   'The Scanning 1 Air-bios',                                       false),
  (461,   'The Uncovered Landmine',                                        false),
  (461.5, 'Volume 42 Side Story',                                          false),
  (462,   'Two Things Only',                                               false),
  (463,   'Fukurou''s Failure',                                            false),
  (464,   'An Intentional Mistake',                                        false),
  (465,   'His True Ally',                                                 false),
  (466,   'A Man Of Diamonds',                                             false),
  (467,   'Deserve To Suffer',                                             false),
  (468,   'Usogui',                                                        false),
  (469,   'Air Poker''s Epilogue',                                         false),
  (470,   'The Slave In His Heart',                                        false),
  (471,   'The Puppets',                                                   false),
  (472,   'After Paying The Price',                                        false),
  (472.5, 'Volume 43 Side Story',                                          false),
  (473,   'Weight',                                                        false),
  (474,   'Leader''s Attendant',                                           false),
  (475,   'No.0 And No.2',                                                 false),
  (476,   'The Entrusted Handkerchiefs',                                   false),
  (477,   'Forest Of Beasts',                                              false),
  (478,   'My Invincible Darling',                                         false),
  (479,   'A Secret In His Life',                                          false),
  (480,   'Something Good Might Happen',                                   false),
  (481,   'A Strange Dream',                                               false),
  (482,   'The Imprisoned Referee',                                        false),
  (483,   'The Most Suitable One',                                         false),
  (483.5, 'Volume 44 Side Story',                                          false),
  (484,   'A Four-way Face-off',                                           false),
  (485,   'The Seeds Of The Private Funeral Division',                     false),
  (486,   'Referee Kadokura',                                              false),
  (487,   'Strongest Barrier',                                             false),
  (488,   'Absolute Zero',                                                 false),
  (489,   'The Man Standing Between The Two',                              false),
  (490,   'Within The Passage Of Time',                                    false),
  (491,   'Squandering And Death',                                         false),
  (492,   'Near-Death Game',                                               false),
  (493,   'Sound Of Time',                                                 false),
  (494,   '''D'' And ''C''',                                               false),
  (494.5, 'Volume 45 Side Story',                                          false),
  (495,   'Stolen Initiative',                                             false),
  (496,   'The 1st Near-Death',                                            false),
  (497,   'A Tricky Disguise',                                             false),
  (498,   'The Gambler Who''s Being Burnt',                                false),
  (499,   'The Hidden Setup',                                              false),
  (500,   'Only Through Death',                                            false),
  (501,   'If You Listen Carefully',                                       false),
  (502,   'Man Of The Neck',                                               false),
  (503,   '2 Strange Feelings',                                            false),
  (504,   'What Must Be Avoided At Any Cost',                              false),
  (505,   'Saying One Thing And Doing Another',                            false),
  (505.5, 'Volume 46 Side Story',                                          false),
  (506,   'The Heart''s Sound',                                            false),
  (507,   'Woman Of Destiny',                                              false),
  (508,   'The Unveiled Destiny',                                          false),
  (509,   'Upside-down',                                                   false),
  (510,   'Domination',                                                    false),
  (511,   'The Second Death',                                              false),
  (512,   'Unbreakable Life',                                              false),
  (513,   'The Continuous Dive',                                           false),
  (514,   'An Extraordinary Person',                                       false),
  (515,   'The Effort He''s Been Putting In',                              false),
  (516,   'One Chance',                                                    false),
  (516.5, 'Volume 47 Side Story',                                          false),
  (517,   'Over The Line',                                                 false),
  (518,   'The Drawer That Disappeared',                                   false),
  (519,   'After Deliberation',                                            false),
  (520,   'The Approaching Crisis',                                        false),
  (521,   'To That Place',                                                 false),
  (522,   'Conviction',                                                    false),
  (523,   'To The Future',                                                 false),
  (524,   'Endings',                                                       false),
  (525,   'The Second Signal',                                             false),
  (526,   'The Man Who Died First',                                        false),
  (527,   'Drawer Of Uncertainty',                                         false),
  (528,   'The Moment He Entered The Route',                               false),
  (528.5, 'Volume 48 Side Story',                                          false),
  (529,   'Howling And Roaring',                                           false),
  (530,   'The Winner Is...',                                              false),
  (531,   'A Clear Ending',                                                false),
  (532,   'A Part Of Myself I Still Can''t See',                           false),
  (533,   'What I Wanted To See',                                          false),
  (534,   'On That Day',                                                   false),
  (535,   'A Small Lie',                                                   false),
  (536,   'Vice Fund',                                                     false),
  (537,   'The Vices',                                                     false),
  (538,   'What Was Coming',                                               false),
  (539,   'Plan A',                                                        false),
  (539.5, 'Volume 49 Side Story',                                          false)
ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title
  WHERE chapter.title IS DISTINCT FROM EXCLUDED.title;

-- =============================================================================
-- Volume boundary verification (these already match — included for reference)
-- If any need correcting, uncomment and adjust:
-- UPDATE volume SET "startChapter" = 1,   "endChapter" = 9   WHERE number = 1;
-- UPDATE volume SET "startChapter" = 10,  "endChapter" = 20  WHERE number = 2;
-- ... etc.
-- =============================================================================
